# Generated by Django 5.2.7 on 2025-10-01 14:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(max_length=500)),
                (
                    "long_description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("website_url", models.URLField(max_length=2083)),
                ("github_url", models.URLField(blank=True, max_length=2083, null=True)),
                ("demo_url", models.URLField(blank=True, max_length=2083, null=True)),
                ("screenshot_urls", models.JSONField(blank=True, default=list)),
                ("tech_stack", models.JSONField(default=list)),
                ("monthly_visitors", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("submission_month", models.CharField(db_index=True, max_length=7)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewer_ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_views",
            },
        ),
    ]
