# Generated by Django 5.2.7 on 2025-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
