# Generated by Django 6.0.1 on 2026-01-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_competition_reviewer_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionreviewer",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
