# Generated by Django 6.0.1 on 2026-01-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_competition_reviewer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_competitions",
                to="projects.project",
            ),
        ),
    ]
