# Generated by Django 6.0.1 on 2026-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_competition_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
