# Generated by Django 6.0.1 on 2026-01-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_category_project_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
