# Generated by Django 6.0.1 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_category_project_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ice_box", "Ice Box"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
