# Generated by Django 6.0.1 on 2026-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_remove_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="quote",
            field=models.TextField(blank=True, null=True),
        ),
    ]
