# Generated by Django 6.0.1 on 2026-01-20 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_add_ice_box_status"),
        ("projects", "0012_add_competition_quote"),
    ]

    operations = []
