# Generated by Django 6.0.1 on 2026-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_merge_20260120_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepting_applications", "Accepting Applications"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
    ]
