# Generated by Django 6.0.1 on 2026-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_add_competition_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="prize_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
