# Generated by Django 6.0.1 on 2026-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_add_competition_prize_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="prize_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
