# Generated by Django 6.0.1 on 2026-01-21 11:06

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_alter_competition_prize_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.projects.models.competition_image_path,
            ),
        ),
    ]
