# Generated by Django 6.0.1 on 2026-01-24 12:04

from django.db import migrations, models
from django.utils.text import slugify

# Icelandic character transliteration for slugs
ICELANDIC_TRANSLITERATION = {
    "á": "a",
    "ð": "d",
    "é": "e",
    "í": "i",
    "ó": "o",
    "ú": "u",
    "ý": "y",
    "þ": "th",
    "æ": "ae",
    "ö": "o",
    "Á": "A",
    "Ð": "D",
    "É": "E",
    "Í": "I",
    "Ó": "O",
    "Ú": "U",
    "Ý": "Y",
    "Þ": "Th",
    "Æ": "Ae",
    "Ö": "O",
}


def transliterate_icelandic(text: str) -> str:
    for icelandic, ascii_equiv in ICELANDIC_TRANSLITERATION.items():
        text = text.replace(icelandic, ascii_equiv)
    return text


def generate_slugs(apps, schema_editor):
    Competition = apps.get_model("projects", "Competition")
    for competition in Competition.objects.all():
        competition.slug = slugify(transliterate_icelandic(competition.name))
        competition.save(update_fields=["slug"])


def reverse_slugs(apps, schema_editor):
    pass  # No action needed on reverse


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_add_competition_image"),
    ]

    operations = [
        # Add field without unique constraint first
        migrations.AddField(
            model_name="competition",
            name="slug",
            field=models.SlugField(blank=True, max_length=110, default=""),
        ),
        # Generate slugs for existing records
        migrations.RunPython(generate_slugs, reverse_slugs),
    ]
