# Generated by Django 6.0.1 on 2026-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_add_competition_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="slug",
            field=models.SlugField(blank=True, max_length=110, unique=True),
        ),
    ]
