# Generated by Django 6.0.1 on 2026-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_competition_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tagline",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
