# Generated by Django 6.0.1 on 2026-02-28 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0021_add_tagline_to_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("thumb", "Thumb (384w)"),
                            ("medium", "Medium (768w)"),
                            ("large", "Large (1536w)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("file_size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="projects.projectimage",
                    ),
                ),
            ],
            options={
                "db_table": "project_image_variants",
                "unique_together": {("image", "size")},
            },
        ),
    ]
