# Generated by Django 6.0.1 on 2026-03-01 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_add_image_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="project",
            name="monthly_visitors",
        ),
    ]
