# Generated by Django 6.0.1 on 2026-03-18 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_remove_project_is_featured_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="approval_status",
            field=models.CharField(
                choices=[("active", "Active"), ("proposed", "Proposed")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("icon", "Icon"),
                    ("screenshot", "Screenshot"),
                    ("main_image", "Main Image"),
                    ("winner_composite", "Winner Composite"),
                ],
                db_index=True,
                default="screenshot",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ImageGenerationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("icon", "Icon"),
                            ("screenshot", "Screenshot"),
                            ("main_image", "Main Image"),
                            ("winner_composite", "Winner Composite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_text", models.TextField()),
                (
                    "device_frame",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("laptop", "Laptop"),
                            ("watch", "Watch"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "leonardo_generation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("leonardo_model_id", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("num_variants", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "reference_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referencing_requests",
                        to="projects.projectimage",
                    ),
                ),
            ],
            options={
                "db_table": "image_generation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="projectimage",
            name="generation_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_images",
                to="projects.imagegenerationrequest",
            ),
        ),
    ]
