# Generated by Django 6.0.1 on 2026-03-20 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_remove_project_is_featured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "project categories",
                "db_table": "project_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("icon", "Icon"),
                    ("hero_banner", "Hero Banner"),
                    ("in_use", "In Use"),
                    ("winner_composite", "Winner Composite"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.projectcategory",
            ),
        ),
    ]
