# Generated by Django 6.0.1 on 2026-03-18 16:53

from django.db import migrations


def migrate_images_to_screenshot(apps, schema_editor):
    ProjectImage = apps.get_model("projects", "ProjectImage")
    ProjectImage.objects.filter(purpose="screenshot", approval_status="active").update(
        purpose="screenshot", approval_status="active"
    )
    # Set any images that might have empty/null values from the schema migration
    ProjectImage.objects.exclude(purpose="screenshot").update(purpose="screenshot")
    ProjectImage.objects.exclude(approval_status="active").update(
        approval_status="active"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0024_add_image_purposes_and_generation"),
    ]

    operations = [
        migrations.RunPython(
            migrate_images_to_screenshot,
            migrations.RunPython.noop,
        ),
    ]
