# Generated by Django 6.0.1 on 2026-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0025_backfill_approved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="is_hero",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="is_usage",
            field=models.BooleanField(default=False),
        ),
    ]
