# Generated by Django 6.0.1 on 2026-03-21 16:22

from django.db import migrations


def migrate_purpose_to_booleans(apps, schema_editor):
    """Convert purpose='hero_banner' and 'in_use' to boolean role fields.

    For each project, if multiple images share the same purpose,
    only the first by display_order gets the boolean flag.
    """
    ProjectImage = apps.get_model("projects", "ProjectImage")

    for purpose, field in [("hero_banner", "is_hero"), ("in_use", "is_usage")]:
        seen_projects = set()
        images = ProjectImage.objects.filter(
            purpose=purpose, upload_status="uploaded"
        ).order_by("display_order", "created_at")

        for image in images:
            if image.project_id not in seen_projects:
                seen_projects.add(image.project_id)
                setattr(image, field, True)
                image.purpose = "general"
                image.save(update_fields=[field, "purpose"])
            else:
                # Duplicate — just reset purpose, don't set boolean
                image.purpose = "general"
                image.save(update_fields=["purpose"])


def reverse_booleans_to_purpose(apps, schema_editor):
    """Reverse: convert boolean flags back to purpose field."""
    ProjectImage = apps.get_model("projects", "ProjectImage")

    for image in ProjectImage.objects.filter(is_hero=True):
        image.purpose = "hero_banner"
        image.is_hero = False
        image.save(update_fields=["purpose", "is_hero"])

    for image in ProjectImage.objects.filter(is_usage=True):
        image.purpose = "in_use"
        image.is_usage = False
        image.save(update_fields=["purpose", "is_usage"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0026_add_is_hero_is_usage_to_projectimage"),
    ]

    operations = [
        migrations.RunPython(
            migrate_purpose_to_booleans,
            reverse_booleans_to_purpose,
        ),
    ]
