# Generated by Django 6.0.1 on 2026-03-21 17:19

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_migrate_purpose_to_role_booleans"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="image_wide",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.projects.models.competition_image_path,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="image_wide_winner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.projects.models.competition_image_path,
            ),
        ),
    ]
