# Generated by Django 6.0.1 on 2026-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0028_add_competition_wide_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="is_icon",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="purpose",
            field=models.CharField(
                choices=[("general", "General"), ("icon", "Icon")],
                default="general",
                max_length=20,
            ),
        ),
    ]
