# Generated by Django 6.0.1 on 2026-03-21 17:50

from django.db import migrations


def backfill_is_icon(apps, schema_editor):
    ProjectImage = apps.get_model("projects", "ProjectImage")
    ProjectImage.objects.filter(purpose="icon").update(is_icon=True)


def reverse_is_icon(apps, schema_editor):
    ProjectImage = apps.get_model("projects", "ProjectImage")
    ProjectImage.objects.filter(is_icon=True).update(purpose="icon")


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0029_add_is_icon_to_projectimage"),
    ]

    operations = [
        migrations.RunPython(backfill_is_icon, reverse_is_icon),
    ]
