# Generated by Django 6.0.1 on 2026-03-21 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_backfill_is_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="purpose",
        ),
    ]
