# Generated by Django 6.0.1 on 2026-04-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_remove_purpose_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepting_applications", "Accepting Applications"),
                    ("voting", "Voting"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
    ]
