# Generated by Django 6.0.1 on 2026-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0034_backfill_voting_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionreviewer",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("ended", "Ended"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
