# Generated by Django 6.0.1 on 2026-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0035_add_ended_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=110, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ice_box", "Ice Box"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submission_month",
            field=models.CharField(blank=True, db_index=True, max_length=7),
        ),
    ]
