# Generated by Django 6.0.1 on 2026-04-29 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_owner_contributors(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectContributor = apps.get_model("projects", "ProjectContributor")

    existing_pairs = set(
        ProjectContributor.objects.values_list("project_id", "user_id")
    )
    rows = []
    for project in Project.objects.exclude(owner__isnull=True).only("id", "owner_id"):
        if (project.id, project.owner_id) in existing_pairs:
            continue
        rows.append(
            ProjectContributor(
                project_id=project.id,
                user_id=project.owner_id,
                role="owner",
                full_edit=True,
            )
        )
    if rows:
        ProjectContributor.objects.bulk_create(rows)


def noop(apps, schema_editor):  # noqa: ARG001
    # The CreateModel reversal drops the table; nothing to undo here.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0037_backfill_slug_and_published_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("suggester", "Suggester")],
                        max_length=20,
                    ),
                ),
                ("full_edit", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_contributors",
                "ordering": ["role", "created_at"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.RunPython(backfill_owner_contributors, noop),
    ]
