# Generated by Django 6.0.1 on 2026-04-29 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0038_projectcontributor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="creator",
        ),
    ]
