# Generated by Django 6.0.1 on 2026-04-29 21:37

from django.db import migrations, models


def rename_suggester_to_tipster(apps, schema_editor):
    ProjectContributor = apps.get_model("projects", "ProjectContributor")
    ProjectContributor.objects.filter(role="suggester").update(role="tipster")


def rename_tipster_to_suggester(apps, schema_editor):
    ProjectContributor = apps.get_model("projects", "ProjectContributor")
    ProjectContributor.objects.filter(role="tipster").update(role="suggester")


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0039_rename_owner_project_creator"),
    ]

    operations = [
        migrations.RunPython(
            rename_suggester_to_tipster,
            reverse_code=rename_tipster_to_suggester,
        ),
        migrations.AlterField(
            model_name="projectcontributor",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("tipster", "Tipster")], max_length=20
            ),
        ),
    ]
