# Generated by Django 6.0.1 on 2026-05-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_rename_suggester_to_tipster"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_community_tipoff",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
