# Generated by Django 6.0.1 on 2026-05-14 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0042_backfill_is_community_tipoff"),
        ("tags", "0004_assign_colors_and_default_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_house_project",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_house_project", True)),
                fields=("is_house_project",),
                name="project_house_singleton",
            ),
        ),
    ]
