# Generated by Django 6.0.1 on 2026-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0043_project_is_house_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="source",
            field=models.CharField(
                choices=[("project", "Project"), ("article", "Article")],
                db_index=True,
                default="project",
                max_length=20,
            ),
        ),
    ]
