# Generated by Django 6.0.1 on 2026-08-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_alter_article_listing_image"),
        ("projects", "0044_projectimage_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="source",
        ),
        migrations.AddField(
            model_name="projectimage",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="articles.article",
            ),
        ),
    ]
