# Generated by Django 6.0.1 on 2026-08-07 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0045_remove_projectimage_source_projectimage_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanedStorageObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "orphaned_storage_objects",
                "indexes": [
                    models.Index(
                        fields=["attempts", "created_at"],
                        name="orphaned_st_attempt_d54c4e_idx",
                    )
                ],
            },
        ),
    ]
