# Generated by Django 6.0.1 on 2026-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0046_orphanedstorageobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="winner_announced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
