# Generated by Django 6.0.1 on 2026-09-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0052_backfill_competition_winner_announced_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("includes_all_users", models.BooleanField(default=False)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reviewer_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviewer_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="reviewer_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="projects.reviewergroup",
            ),
        ),
    ]
