# Generated by Django 6.0.1 on 2026-09-29 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0052_backfill_competition_winner_announced_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("site_down", "The site won't load"),
                            ("something_broken", "Something on the site is broken"),
                            ("wrong_link", "The link goes somewhere else"),
                            ("other", "Something else"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=2000)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("makers_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
