# Generated by Django 6.0.1 on 2026-09-30 16:10

import apps.projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0054_seed_reviewer_groups_and_prune_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="reviewer_group",
            field=models.ForeignKey(
                default=apps.projects.models.everyone_reviewer_group_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="projects.reviewergroup",
            ),
        ),
        migrations.AlterField(
            model_name="competitionreviewer",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
