# Generated by Django 6.0.1 on 2026-02-06 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body_markdown",
                    models.TextField(
                        help_text="Write the email body in Markdown format."
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("platform_updates", "Platform Updates"),
                            ("competition_results", "Competition Results"),
                        ],
                        help_text="If set, sends to all users opted in to this type. If blank, uses individual recipients below.",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_emails_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "individual_recipients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select individual users (only used when email type is blank).",
                        related_name="broadcast_emails_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_emails_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastEmailRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "broadcast_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_records",
                        to="emails.broadcastemail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_email_recipients",
                "unique_together": {("broadcast_email", "user")},
            },
        ),
    ]
