# Generated by Django 6.0.1 on 2026-02-06 23:03

import apps.emails.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastemail",
            name="body_markdown",
            field=models.TextField(
                help_text="Write the email body in Markdown format. Upload images below, then click Insert to add them."
            ),
        ),
        migrations.CreateModel(
            name="BroadcastEmailImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.emails.models._broadcast_image_storage,
                        upload_to=apps.emails.models._broadcast_image_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="emails.broadcastemail",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_email_images",
                "ordering": ["created_at"],
            },
        ),
    ]
