# Generated by Django 6.0.1 on 2026-03-04 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_add_broadcastemailimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("password_reset", "Password Reset"),
                            ("project_approved", "Project Approved"),
                            ("discussion_notification", "Discussion Notification"),
                            ("discussion_digest", "Discussion Digest"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("to_email", models.EmailField(max_length=254)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sent_emails",
                "ordering": ["-created_at"],
            },
        ),
    ]
