# Generated by Django 6.0.1 on 2026-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0005_change_sentemail_recipient_to_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued_for_sending", "Queued for Sending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
