# Generated by Django 6.0.1 on 2026-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_add_broadcast_email_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("password_reset", "Password Reset"),
                    ("project_approved", "Project Approved"),
                    ("new_project_notification", "New Project Notification"),
                    ("discussion_notification", "Discussion Notification"),
                    ("discussion_digest", "Discussion Digest"),
                ],
                max_length=30,
            ),
        ),
    ]
