# Generated by Django 6.0.1 on 2026-05-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0007_alter_sentemail_email_type"),
        ("projects", "0042_backfill_is_community_tipoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to="projects.project",
            ),
        ),
    ]
