# Generated by Django 6.0.1 on 2026-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0009_alter_sentemail_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("password_reset", "Password Reset"),
                    ("project_approved", "Project Approved"),
                    ("new_project_notification", "New Project Notification"),
                    ("discussion_notification", "Discussion Notification"),
                    ("discussion_digest", "Discussion Digest"),
                    ("article_notification", "Article Notification (legacy)"),
                    ("article_digest", "Article Digest"),
                ],
                max_length=30,
            ),
        ),
    ]
