# Generated by Django 6.0.1 on 2026-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0010_alter_sentemail_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastemail",
            name="email_type",
            field=models.CharField(
                blank=True,
                choices=[("competition_results", "Competition Results")],
                help_text="If set, sends to all users opted in to this type. If blank, uses individual recipients below.",
                max_length=30,
                null=True,
            ),
        ),
    ]
