# Generated by Django 6.0.1 on 2026-02-02 22:35

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    TagCategory = apps.get_model("tags", "TagCategory")

    categories = [
        {
            "name": "Tech Stack",
            "slug": "tech-stack",
            "description": "Technologies and frameworks used in the project",
            "display_order": 0,
        },
        {
            "name": "Project Status",
            "slug": "project-status",
            "description": "Current status of the project (e.g., MVP, Production)",
            "display_order": 1,
        },
        {
            "name": "Funding Status",
            "slug": "funding-status",
            "description": "Funding stage of the project",
            "display_order": 2,
        },
        {
            "name": "Project Type",
            "slug": "project-type",
            "description": "Type of the project (e.g., Web App, Mobile App, API)",
            "display_order": 3,
        },
    ]

    for category in categories:
        TagCategory.objects.create(**category)


def remove_initial_categories(apps, schema_editor):
    TagCategory = apps.get_model("tags", "TagCategory")
    TagCategory.objects.filter(
        slug__in=["tech-stack", "project-status", "funding-status", "project-type"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_add_tag_category_and_status"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
