# Generated by Django 6.0.1 on 2026-04-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(db_index=True, max_length=16)),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("text", models.TextField()),
                ("source_hash", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_machine_translated", models.BooleanField(default=False)),
                ("retired", models.BooleanField(default=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["locale", "retired"],
                        name="translation_locale_54b8d3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("locale", "key"), name="uniq_translation_locale_key"
                    )
                ],
            },
        ),
    ]
