# Generated by Django 6.0.1 on 2026-04-22 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(max_length=16)),
                ("key", models.CharField(max_length=255)),
                ("old_text", models.TextField(blank=True)),
                ("new_text", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="audits",
                        to="translations.translation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["translation", "changed_at"],
                        name="translation_transla_8301e3_idx",
                    ),
                    models.Index(
                        fields=["locale", "key"], name="translation_locale_80d916_idx"
                    ),
                ],
            },
        ),
    ]
