# Generated by Django 6.0.1 on 2026-05-23 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("follows", "0002_seed_channels_and_house_follows"),
        ("projects", "0043_project_is_house_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "global_visibility",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-approved (trusted author)"),
                            ("pending", "Pending admin review"),
                            ("approved", "Admin-approved"),
                            ("demoted", "Demoted"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="follows.channel",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hero_for_articles",
                        to="projects.projectimage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-published_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("slug__isnull", False)),
                        fields=("project", "slug"),
                        name="articles_project_slug_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("external_url__isnull", True), ("source", "internal")
                            ),
                            models.Q(
                                ("external_url__isnull", False), ("source", "external")
                            ),
                            _connector="OR",
                        ),
                        name="articles_source_external_url_consistent",
                    ),
                ],
            },
        ),
    ]
