# Generated by Django 6.0.1 on 2026-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
