# Generated by Django 6.0.1 on 2026-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="card_crop",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="hero_crop",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
