# Generated by Django 6.0.1 on 2026-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_card_crop_article_hero_crop"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="card_crop",
            new_name="listing_crop",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="hero_image",
            new_name="listing_image",
        ),
        migrations.RemoveField(
            model_name="article",
            name="hero_crop",
        ),
        migrations.AddField(
            model_name="article",
            name="listing_image_mode",
            field=models.CharField(
                choices=[
                    ("auto", "First image uploaded to the article"),
                    ("chosen", "Author's choice"),
                    ("none", "No image"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
    ]
