# Generated by Django 6.0.1 on 2026-08-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_rename_card_crop_article_listing_crop_and_more"),
        ("projects", "0044_projectimage_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_for_articles",
                to="projects.projectimage",
            ),
        ),
    ]
