# Generated by Django 6.0.1 on 2026-08-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_alter_article_listing_image"),
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="about_feed_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_up_by",
                to="feed.feedevent",
            ),
        ),
    ]
