# Generated by Django 6.0.1 on 2026-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_article_about_feed_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
