# Generated by Django 6.0.1 on 2026-10-02 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_backfill_article_approved_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="about_feed_event",
        ),
    ]
