# Generated by Django 5.2.7 on 2025-11-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kennitala",
            field=models.CharField(
                db_index=True,
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
