# Generated by Django 6.0.1 on 2026-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_username_add_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
