# Generated by Django 6.0.1 on 2026-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_info_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_opt_in_competition_results",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_opt_in_platform_updates",
            field=models.BooleanField(default=True),
        ),
    ]
