# Generated by Django 6.0.1 on 2026-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_opt_in_to_external_promotions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Every Time"),
                    ("hourly", "At most every hour"),
                    ("daily", "At most every day"),
                    ("never", "Never"),
                ],
                default="immediate",
                max_length=20,
            ),
        ),
    ]
