# Generated by Django 6.0.1 on 2026-03-02 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_add_password_reset_code"),
        ("users", "0008_user_notification_frequency"),
    ]

    operations = []
