# Generated by Django 6.0.1 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_merge_20260302_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Every Time"),
                    ("hourly", "At most every hour"),
                    ("daily", "At most every day"),
                    ("never", "Never"),
                ],
                default="never",
                max_length=20,
            ),
        ),
    ]
