# Generated by Django 6.0.1 on 2026-03-04 18:53

from django.db import migrations


def set_all_users_to_never(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(notification_frequency="never")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_notification_frequency"),
    ]

    operations = [
        migrations.RunPython(set_all_users_to_never, migrations.RunPython.noop),
    ]
