# Generated by Django 6.0.1 on 2026-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_default_notification_frequency_hourly"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_user",
            field=models.BooleanField(default=False),
        ),
    ]
