# Generated by Django 6.0.1 on 2026-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_community_user_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="article_trust",
            field=models.BooleanField(default=True),
        ),
    ]
