# Generated by Django 6.0.1 on 2026-05-29 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_article_trust"),
        # The Phase-1 seed reads (SELECTs) the email_opt_in_* columns, and has
        # no users-app dependency of its own — so pin the drop to run after it,
        # otherwise a fresh-DB migrate could drop the columns first and the
        # seed's SELECT would reference a column that no longer exists.
        ("follows", "0002_seed_channels_and_house_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_opt_in_competition_results",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_opt_in_platform_updates",
        ),
    ]
