# Generated by Django 6.0.1 on 2026-08-14 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0005_alter_article_listing_image"),
        ("discussions", "0001_initial"),
        # The tables this one points at, not whatever `projects` happened to be
        # at when it was generated. Pinning the leaf makes every test that
        # rewinds `projects` drag `feed` back with it.
        ("projects", "0046_orphanedstorageobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("article_published", "Article published"),
                            ("project_published", "Project published"),
                            ("project_tipoff", "Community tipoff"),
                            ("competition_opened", "Competition opened"),
                            ("competition_closed", "Competition closed"),
                            ("competition_winner", "Competition winner announced"),
                            ("discussion_promoted", "Discussion promoted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="articles.article",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="projects.competition",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="discussions.discussion",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="projects.project",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="feed.feedevent",
                    ),
                ),
            ],
            options={
                "db_table": "feed_events",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-occurred_at", "-created_at"],
                        name="feed_events_occurred_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("retired_at__isnull", True),
                            ("superseded_by__isnull", True),
                        ),
                        fields=["-occurred_at"],
                        name="feed_events_live_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", False)),
                        fields=("project",),
                        name="feed_events_project_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("article__isnull", False)),
                        fields=("article",),
                        name="feed_events_article_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("competition__isnull", False)),
                        fields=("kind", "competition"),
                        name="feed_events_kind_competition_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("discussion__isnull", False)),
                        fields=("discussion",),
                        name="feed_events_discussion_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("project__isnull", False),
                            ("article__isnull", False),
                            ("competition__isnull", False),
                            ("discussion__isnull", False),
                            _connector="OR",
                        ),
                        name="feed_events_has_subject",
                    ),
                ],
            },
        ),
    ]
