# Generated by Django 6.0.1 on 2026-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    # Only `feed` itself: see 0001 for why the leaves of the apps this table
    # points at are not pinned here.
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedevent",
            name="feed_events_live_idx",
        ),
        migrations.AddIndex(
            model_name="feedevent",
            index=models.Index(
                condition=models.Q(("retired_at__isnull", True)),
                fields=["-occurred_at"],
                name="feed_events_live_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="feedevent",
            name="superseded_by",
        ),
    ]
