# Generated by Django 6.0.1 on 2026-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0003_delete_competition_events"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedevent",
            name="feed_events_kind_competition_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="feedevent",
            name="feed_events_has_subject",
        ),
        migrations.AlterField(
            model_name="feedevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("article_published", "Article published"),
                    ("project_published", "Project published"),
                    ("project_tipoff", "Community tipoff"),
                    ("discussion_promoted", "Discussion promoted"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="feedevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("project__isnull", False),
                    ("article__isnull", False),
                    ("discussion__isnull", False),
                    _connector="OR",
                ),
                name="feed_events_has_subject",
            ),
        ),
        migrations.RemoveField(
            model_name="feedevent",
            name="competition",
        ),
    ]
