# Generated by Django 6.0.1 on 2026-05-23 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
        ("discussions", "0001_initial"),
        ("notifications", "0003_mark_existing_read_and_dedupe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notifications_recip_disc_uniq",
        ),
        migrations.AddField(
            model_name="notification",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="discussion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="discussions.discussion",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("discussion__isnull", False)),
                fields=("recipient", "discussion"),
                name="notifications_recip_disc_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("article__isnull", False)),
                fields=("recipient", "article"),
                name="notifications_recip_article_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("article__isnull", True), ("discussion__isnull", False)),
                    models.Q(("article__isnull", False), ("discussion__isnull", True)),
                    _connector="OR",
                ),
                name="notifications_target_xor",
            ),
        ),
    ]
