# Generated by Django 6.0.1 on 2026-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_article_fk_and_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="email_cadence",
            field=models.CharField(
                choices=[
                    ("immediate", "Every Time"),
                    ("hourly", "At most every hour"),
                    ("daily", "At most every day"),
                    ("weekly", "At most every week"),
                    ("never", "Never"),
                ],
                max_length=20,
            ),
        ),
    ]
